// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Translation.proto

package jp.go.nict.langrid.client.protobuf.proto;

public final class TranslationProtos {
  private TranslationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TranslateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:translation.TranslateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Header headers = 1;</code>
     */
    java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> 
        getHeadersList();
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index);
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    int getHeadersCount();
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    java.util.List<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
        getHeadersOrBuilderList();
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder getHeadersOrBuilder(
        int index);

    /**
     * <code>required string sourceLang = 2;</code>
     * @return Whether the sourceLang field is set.
     */
    boolean hasSourceLang();
    /**
     * <code>required string sourceLang = 2;</code>
     * @return The sourceLang.
     */
    java.lang.String getSourceLang();
    /**
     * <code>required string sourceLang = 2;</code>
     * @return The bytes for sourceLang.
     */
    com.google.protobuf.ByteString
        getSourceLangBytes();

    /**
     * <code>required string targetLang = 3;</code>
     * @return Whether the targetLang field is set.
     */
    boolean hasTargetLang();
    /**
     * <code>required string targetLang = 3;</code>
     * @return The targetLang.
     */
    java.lang.String getTargetLang();
    /**
     * <code>required string targetLang = 3;</code>
     * @return The bytes for targetLang.
     */
    com.google.protobuf.ByteString
        getTargetLangBytes();

    /**
     * <code>required string source = 4;</code>
     * @return Whether the source field is set.
     */
    boolean hasSource();
    /**
     * <code>required string source = 4;</code>
     * @return The source.
     */
    java.lang.String getSource();
    /**
     * <code>required string source = 4;</code>
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString
        getSourceBytes();
  }
  /**
   * Protobuf type {@code translation.TranslateRequest}
   */
  public static final class TranslateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:translation.TranslateRequest)
      TranslateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TranslateRequest.newBuilder() to construct.
    private TranslateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TranslateRequest() {
      headers_ = java.util.Collections.emptyList();
      sourceLang_ = "";
      targetLang_ = "";
      source_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TranslateRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TranslateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
                mutable_bitField0_ |= 0x00000001;
              }
              headers_.add(
                  input.readMessage(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sourceLang_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              targetLang_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              source_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.class, jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.Builder.class);
    }

    private int bitField0_;
    public static final int HEADERS_FIELD_NUMBER = 1;
    private java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> headers_;
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
      return headers_;
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
        getHeadersOrBuilderList() {
      return headers_;
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public int getHeadersCount() {
      return headers_.size();
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
      return headers_.get(index);
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder getHeadersOrBuilder(
        int index) {
      return headers_.get(index);
    }

    public static final int SOURCELANG_FIELD_NUMBER = 2;
    private volatile java.lang.Object sourceLang_;
    /**
     * <code>required string sourceLang = 2;</code>
     * @return Whether the sourceLang field is set.
     */
    @java.lang.Override
    public boolean hasSourceLang() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string sourceLang = 2;</code>
     * @return The sourceLang.
     */
    @java.lang.Override
    public java.lang.String getSourceLang() {
      java.lang.Object ref = sourceLang_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceLang_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sourceLang = 2;</code>
     * @return The bytes for sourceLang.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceLangBytes() {
      java.lang.Object ref = sourceLang_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceLang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGETLANG_FIELD_NUMBER = 3;
    private volatile java.lang.Object targetLang_;
    /**
     * <code>required string targetLang = 3;</code>
     * @return Whether the targetLang field is set.
     */
    @java.lang.Override
    public boolean hasTargetLang() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string targetLang = 3;</code>
     * @return The targetLang.
     */
    @java.lang.Override
    public java.lang.String getTargetLang() {
      java.lang.Object ref = targetLang_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetLang_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string targetLang = 3;</code>
     * @return The bytes for targetLang.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetLangBytes() {
      java.lang.Object ref = targetLang_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetLang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private volatile java.lang.Object source_;
    /**
     * <code>required string source = 4;</code>
     * @return Whether the source field is set.
     */
    @java.lang.Override
    public boolean hasSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string source = 4;</code>
     * @return The source.
     */
    @java.lang.Override
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string source = 4;</code>
     * @return The bytes for source.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSourceLang()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetLang()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHeadersCount(); i++) {
        if (!getHeaders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < headers_.size(); i++) {
        output.writeMessage(1, headers_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceLang_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, targetLang_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, source_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < headers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, headers_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceLang_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, targetLang_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, source_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest)) {
        return super.equals(obj);
      }
      jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest other = (jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest) obj;

      if (!getHeadersList()
          .equals(other.getHeadersList())) return false;
      if (hasSourceLang() != other.hasSourceLang()) return false;
      if (hasSourceLang()) {
        if (!getSourceLang()
            .equals(other.getSourceLang())) return false;
      }
      if (hasTargetLang() != other.hasTargetLang()) return false;
      if (hasTargetLang()) {
        if (!getTargetLang()
            .equals(other.getTargetLang())) return false;
      }
      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (!getSource()
            .equals(other.getSource())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHeadersCount() > 0) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHeadersList().hashCode();
      }
      if (hasSourceLang()) {
        hash = (37 * hash) + SOURCELANG_FIELD_NUMBER;
        hash = (53 * hash) + getSourceLang().hashCode();
      }
      if (hasTargetLang()) {
        hash = (37 * hash) + TARGETLANG_FIELD_NUMBER;
        hash = (53 * hash) + getTargetLang().hashCode();
      }
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code translation.TranslateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:translation.TranslateRequest)
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.class, jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.Builder.class);
      }

      // Construct using jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeadersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          headersBuilder_.clear();
        }
        sourceLang_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        targetLang_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateRequest_descriptor;
      }

      @java.lang.Override
      public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest getDefaultInstanceForType() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest build() {
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest buildPartial() {
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest result = new jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (headersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            headers_ = java.util.Collections.unmodifiableList(headers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.headers_ = headers_;
        } else {
          result.headers_ = headersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sourceLang_ = sourceLang_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.targetLang_ = targetLang_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.source_ = source_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest) {
          return mergeFrom((jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest other) {
        if (other == jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest.getDefaultInstance()) return this;
        if (headersBuilder_ == null) {
          if (!other.headers_.isEmpty()) {
            if (headers_.isEmpty()) {
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeadersIsMutable();
              headers_.addAll(other.headers_);
            }
            onChanged();
          }
        } else {
          if (!other.headers_.isEmpty()) {
            if (headersBuilder_.isEmpty()) {
              headersBuilder_.dispose();
              headersBuilder_ = null;
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              headersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeadersFieldBuilder() : null;
            } else {
              headersBuilder_.addAllMessages(other.headers_);
            }
          }
        }
        if (other.hasSourceLang()) {
          bitField0_ |= 0x00000002;
          sourceLang_ = other.sourceLang_;
          onChanged();
        }
        if (other.hasTargetLang()) {
          bitField0_ |= 0x00000004;
          targetLang_ = other.targetLang_;
          onChanged();
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000008;
          source_ = other.source_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSourceLang()) {
          return false;
        }
        if (!hasTargetLang()) {
          return false;
        }
        if (!hasSource()) {
          return false;
        }
        for (int i = 0; i < getHeadersCount(); i++) {
          if (!getHeaders(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> headers_ =
        java.util.Collections.emptyList();
      private void ensureHeadersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>(headers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> headersBuilder_;

      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
        if (headersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(headers_);
        } else {
          return headersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public int getHeadersCount() {
        if (headersBuilder_ == null) {
          return headers_.size();
        } else {
          return headersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);
        } else {
          return headersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder setHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.set(index, value);
          onChanged();
        } else {
          headersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder setHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.set(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(value);
          onChanged();
        } else {
          headersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(index, value);
          onChanged();
        } else {
          headersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addAllHeaders(
          java.lang.Iterable<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> values) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, headers_);
          onChanged();
        } else {
          headersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder clearHeaders() {
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          headersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder removeHeaders(int index) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.remove(index);
          onChanged();
        } else {
          headersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder getHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder getHeadersOrBuilder(
          int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);  } else {
          return headersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public java.util.List<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
           getHeadersOrBuilderList() {
        if (headersBuilder_ != null) {
          return headersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(headers_);
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder addHeadersBuilder() {
        return getHeadersFieldBuilder().addBuilder(
            jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder addHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().addBuilder(
            index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder> 
           getHeadersBuilderList() {
        return getHeadersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
          getHeadersFieldBuilder() {
        if (headersBuilder_ == null) {
          headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder>(
                  headers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          headers_ = null;
        }
        return headersBuilder_;
      }

      private java.lang.Object sourceLang_ = "";
      /**
       * <code>required string sourceLang = 2;</code>
       * @return Whether the sourceLang field is set.
       */
      public boolean hasSourceLang() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string sourceLang = 2;</code>
       * @return The sourceLang.
       */
      public java.lang.String getSourceLang() {
        java.lang.Object ref = sourceLang_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceLang_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sourceLang = 2;</code>
       * @return The bytes for sourceLang.
       */
      public com.google.protobuf.ByteString
          getSourceLangBytes() {
        java.lang.Object ref = sourceLang_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceLang_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sourceLang = 2;</code>
       * @param value The sourceLang to set.
       * @return This builder for chaining.
       */
      public Builder setSourceLang(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceLang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sourceLang = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceLang() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceLang_ = getDefaultInstance().getSourceLang();
        onChanged();
        return this;
      }
      /**
       * <code>required string sourceLang = 2;</code>
       * @param value The bytes for sourceLang to set.
       * @return This builder for chaining.
       */
      public Builder setSourceLangBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceLang_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetLang_ = "";
      /**
       * <code>required string targetLang = 3;</code>
       * @return Whether the targetLang field is set.
       */
      public boolean hasTargetLang() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string targetLang = 3;</code>
       * @return The targetLang.
       */
      public java.lang.String getTargetLang() {
        java.lang.Object ref = targetLang_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetLang_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string targetLang = 3;</code>
       * @return The bytes for targetLang.
       */
      public com.google.protobuf.ByteString
          getTargetLangBytes() {
        java.lang.Object ref = targetLang_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetLang_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string targetLang = 3;</code>
       * @param value The targetLang to set.
       * @return This builder for chaining.
       */
      public Builder setTargetLang(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        targetLang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string targetLang = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetLang() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetLang_ = getDefaultInstance().getTargetLang();
        onChanged();
        return this;
      }
      /**
       * <code>required string targetLang = 3;</code>
       * @param value The bytes for targetLang to set.
       * @return This builder for chaining.
       */
      public Builder setTargetLangBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        targetLang_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>required string source = 4;</code>
       * @return Whether the source field is set.
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string source = 4;</code>
       * @return The source.
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string source = 4;</code>
       * @return The bytes for source.
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string source = 4;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string source = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000008);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>required string source = 4;</code>
       * @param value The bytes for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        source_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:translation.TranslateRequest)
    }

    // @@protoc_insertion_point(class_scope:translation.TranslateRequest)
    private static final jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest();
    }

    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TranslateRequest>
        PARSER = new com.google.protobuf.AbstractParser<TranslateRequest>() {
      @java.lang.Override
      public TranslateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TranslateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TranslateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranslateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TranslateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:translation.TranslateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Header headers = 1;</code>
     */
    java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> 
        getHeadersList();
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index);
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    int getHeadersCount();
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    java.util.List<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
        getHeadersOrBuilderList();
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder getHeadersOrBuilder(
        int index);

    /**
     * <code>optional .Fault fault = 2;</code>
     * @return Whether the fault field is set.
     */
    boolean hasFault();
    /**
     * <code>optional .Fault fault = 2;</code>
     * @return The fault.
     */
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault getFault();
    /**
     * <code>optional .Fault fault = 2;</code>
     */
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.FaultOrBuilder getFaultOrBuilder();

    /**
     * <code>optional string result = 3;</code>
     * @return Whether the result field is set.
     */
    boolean hasResult();
    /**
     * <code>optional string result = 3;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>optional string result = 3;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code translation.TranslateResponse}
   */
  public static final class TranslateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:translation.TranslateResponse)
      TranslateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TranslateResponse.newBuilder() to construct.
    private TranslateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TranslateResponse() {
      headers_ = java.util.Collections.emptyList();
      result_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TranslateResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TranslateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
                mutable_bitField0_ |= 0x00000001;
              }
              headers_.add(
                  input.readMessage(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = fault_.toBuilder();
              }
              fault_ = input.readMessage(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fault_);
                fault_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              result_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.class, jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.Builder.class);
    }

    private int bitField0_;
    public static final int HEADERS_FIELD_NUMBER = 1;
    private java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> headers_;
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
      return headers_;
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
        getHeadersOrBuilderList() {
      return headers_;
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public int getHeadersCount() {
      return headers_.size();
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
      return headers_.get(index);
    }
    /**
     * <code>repeated .Header headers = 1;</code>
     */
    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder getHeadersOrBuilder(
        int index) {
      return headers_.get(index);
    }

    public static final int FAULT_FIELD_NUMBER = 2;
    private jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault fault_;
    /**
     * <code>optional .Fault fault = 2;</code>
     * @return Whether the fault field is set.
     */
    @java.lang.Override
    public boolean hasFault() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Fault fault = 2;</code>
     * @return The fault.
     */
    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault getFault() {
      return fault_ == null ? jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance() : fault_;
    }
    /**
     * <code>optional .Fault fault = 2;</code>
     */
    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.FaultOrBuilder getFaultOrBuilder() {
      return fault_ == null ? jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance() : fault_;
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private volatile java.lang.Object result_;
    /**
     * <code>optional string result = 3;</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string result = 3;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result = 3;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHeadersCount(); i++) {
        if (!getHeaders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasFault()) {
        if (!getFault().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < headers_.size(); i++) {
        output.writeMessage(1, headers_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getFault());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < headers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, headers_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFault());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse)) {
        return super.equals(obj);
      }
      jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse other = (jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse) obj;

      if (!getHeadersList()
          .equals(other.getHeadersList())) return false;
      if (hasFault() != other.hasFault()) return false;
      if (hasFault()) {
        if (!getFault()
            .equals(other.getFault())) return false;
      }
      if (hasResult() != other.hasResult()) return false;
      if (hasResult()) {
        if (!getResult()
            .equals(other.getResult())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHeadersCount() > 0) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHeadersList().hashCode();
      }
      if (hasFault()) {
        hash = (37 * hash) + FAULT_FIELD_NUMBER;
        hash = (53 * hash) + getFault().hashCode();
      }
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code translation.TranslateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:translation.TranslateResponse)
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.class, jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.Builder.class);
      }

      // Construct using jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeadersFieldBuilder();
          getFaultFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          headersBuilder_.clear();
        }
        if (faultBuilder_ == null) {
          fault_ = null;
        } else {
          faultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.internal_static_translation_TranslateResponse_descriptor;
      }

      @java.lang.Override
      public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse getDefaultInstanceForType() {
        return jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse build() {
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse buildPartial() {
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse result = new jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (headersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            headers_ = java.util.Collections.unmodifiableList(headers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.headers_ = headers_;
        } else {
          result.headers_ = headersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (faultBuilder_ == null) {
            result.fault_ = fault_;
          } else {
            result.fault_ = faultBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse) {
          return mergeFrom((jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse other) {
        if (other == jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse.getDefaultInstance()) return this;
        if (headersBuilder_ == null) {
          if (!other.headers_.isEmpty()) {
            if (headers_.isEmpty()) {
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeadersIsMutable();
              headers_.addAll(other.headers_);
            }
            onChanged();
          }
        } else {
          if (!other.headers_.isEmpty()) {
            if (headersBuilder_.isEmpty()) {
              headersBuilder_.dispose();
              headersBuilder_ = null;
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              headersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeadersFieldBuilder() : null;
            } else {
              headersBuilder_.addAllMessages(other.headers_);
            }
          }
        }
        if (other.hasFault()) {
          mergeFault(other.getFault());
        }
        if (other.hasResult()) {
          bitField0_ |= 0x00000004;
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getHeadersCount(); i++) {
          if (!getHeaders(i).isInitialized()) {
            return false;
          }
        }
        if (hasFault()) {
          if (!getFault().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> headers_ =
        java.util.Collections.emptyList();
      private void ensureHeadersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>(headers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> headersBuilder_;

      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
        if (headersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(headers_);
        } else {
          return headersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public int getHeadersCount() {
        if (headersBuilder_ == null) {
          return headers_.size();
        } else {
          return headersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);
        } else {
          return headersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder setHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.set(index, value);
          onChanged();
        } else {
          headersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder setHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.set(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(value);
          onChanged();
        } else {
          headersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(index, value);
          onChanged();
        } else {
          headersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addHeaders(
          int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder addAllHeaders(
          java.lang.Iterable<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> values) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, headers_);
          onChanged();
        } else {
          headersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder clearHeaders() {
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          headersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public Builder removeHeaders(int index) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.remove(index);
          onChanged();
        } else {
          headersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder getHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder getHeadersOrBuilder(
          int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);  } else {
          return headersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public java.util.List<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
           getHeadersOrBuilderList() {
        if (headersBuilder_ != null) {
          return headersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(headers_);
        }
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder addHeadersBuilder() {
        return getHeadersFieldBuilder().addBuilder(
            jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder addHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().addBuilder(
            index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .Header headers = 1;</code>
       */
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder> 
           getHeadersBuilderList() {
        return getHeadersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder> 
          getHeadersFieldBuilder() {
        if (headersBuilder_ == null) {
          headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.HeaderOrBuilder>(
                  headers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          headers_ = null;
        }
        return headersBuilder_;
      }

      private jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault fault_;
      private com.google.protobuf.SingleFieldBuilderV3<
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.FaultOrBuilder> faultBuilder_;
      /**
       * <code>optional .Fault fault = 2;</code>
       * @return Whether the fault field is set.
       */
      public boolean hasFault() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       * @return The fault.
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault getFault() {
        if (faultBuilder_ == null) {
          return fault_ == null ? jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance() : fault_;
        } else {
          return faultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      public Builder setFault(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault value) {
        if (faultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fault_ = value;
          onChanged();
        } else {
          faultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      public Builder setFault(
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder builderForValue) {
        if (faultBuilder_ == null) {
          fault_ = builderForValue.build();
          onChanged();
        } else {
          faultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      public Builder mergeFault(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault value) {
        if (faultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              fault_ != null &&
              fault_ != jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance()) {
            fault_ =
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.newBuilder(fault_).mergeFrom(value).buildPartial();
          } else {
            fault_ = value;
          }
          onChanged();
        } else {
          faultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      public Builder clearFault() {
        if (faultBuilder_ == null) {
          fault_ = null;
          onChanged();
        } else {
          faultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder getFaultBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFaultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.FaultOrBuilder getFaultOrBuilder() {
        if (faultBuilder_ != null) {
          return faultBuilder_.getMessageOrBuilder();
        } else {
          return fault_ == null ?
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance() : fault_;
        }
      }
      /**
       * <code>optional .Fault fault = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.FaultOrBuilder> 
          getFaultFieldBuilder() {
        if (faultBuilder_ == null) {
          faultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.FaultOrBuilder>(
                  getFault(),
                  getParentForChildren(),
                  isClean());
          fault_ = null;
        }
        return faultBuilder_;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>optional string result = 3;</code>
       * @return Whether the result field is set.
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string result = 3;</code>
       * @return The result.
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result = 3;</code>
       * @return The bytes for result.
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 3;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 3;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        result_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:translation.TranslateResponse)
    }

    // @@protoc_insertion_point(class_scope:translation.TranslateResponse)
    private static final jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse();
    }

    public static jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TranslateResponse>
        PARSER = new com.google.protobuf.AbstractParser<TranslateResponse>() {
      @java.lang.Override
      public TranslateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TranslateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TranslateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranslateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public jp.go.nict.langrid.client.protobuf.proto.TranslationProtos.TranslateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_translation_TranslateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_translation_TranslateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_translation_TranslateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_translation_TranslateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Translation.proto\022\013translation\032\014common" +
      ".proto\"d\n\020TranslateRequest\022\030\n\007headers\030\001 " +
      "\003(\0132\007.Header\022\022\n\nsourceLang\030\002 \002(\t\022\022\n\ntarg" +
      "etLang\030\003 \002(\t\022\016\n\006source\030\004 \002(\t\"T\n\021Translat" +
      "eResponse\022\030\n\007headers\030\001 \003(\0132\007.Header\022\025\n\005f" +
      "ault\030\002 \001(\0132\006.Fault\022\016\n\006result\030\003 \001(\t2U\n\007Se" +
      "rvice\022J\n\ttranslate\022\035.translation.Transla" +
      "teRequest\032\036.translation.TranslateRespons" +
      "eB=\n(jp.go.nict.langrid.client.protobuf." +
      "protoB\021TranslationProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.getDescriptor(),
        });
    internal_static_translation_TranslateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_translation_TranslateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_translation_TranslateRequest_descriptor,
        new java.lang.String[] { "Headers", "SourceLang", "TargetLang", "Source", });
    internal_static_translation_TranslateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_translation_TranslateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_translation_TranslateResponse_descriptor,
        new java.lang.String[] { "Headers", "Fault", "Result", });
    jp.go.nict.langrid.client.protobuf.proto.CommonProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
