/**
 * ServiceManagement.java
 *
 * このファイルはWSDLから自動生成されました / [en]-(This file was auto-generated from WSDL)
 * Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java生成器によって / [en]-(by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.)
 */

package localhost.langrid_2_0.services.ServiceManagement;

public interface ServiceManagement extends java.rmi.Remote {
    public byte[] getServiceWsdl(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceEntrySearchResult searchServices(int startIndex, int maxCount, jp.go.nict.langrid.ws_1_2.foundation.MatchingCondition[] conditions, jp.go.nict.langrid.ws_1_2.foundation.Order[] orders, java.lang.String scope) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.UnsupportedMatchingMethodException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceInstance getServiceInstance(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void activateService(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceNotActivatableException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void deactivateService(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceNotDeactivatableException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void deleteService(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceNotInactiveException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public boolean isServiceActive(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.Invocation[] getExternalInvocations(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceEntryWithCompactLanguageExpressionSearchResult searchServicesWithCompactLanguageExpression(int startIndex, int maxCount, jp.go.nict.langrid.ws_1_2.foundation.MatchingCondition[] conditions, jp.go.nict.langrid.ws_1_2.foundation.Order[] orders, java.lang.String scope) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.UnsupportedMatchingMethodException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.CompositeServiceEntrySearchResult searchCompositeServices(int startIndex, int maxCount, jp.go.nict.langrid.ws_1_2.foundation.MatchingCondition[] conditions, jp.go.nict.langrid.ws_1_2.foundation.Order[] orders, java.lang.String scope) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.UnsupportedMatchingMethodException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void addServiceAs(java.lang.String ownerUserId, java.lang.String serviceId, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceProfile profile, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceInstance instance, jp.go.nict.langrid.ws_1_2.foundation.Attribute[] attributes) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceAlreadyExistsException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceProfile getServiceProfile(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setServiceProfile(java.lang.String serviceId, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceProfile profile) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.Attribute[] getServiceAttributes(java.lang.String serviceId, java.lang.String[] attributeNames) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setServiceAttributes(java.lang.String serviceId, jp.go.nict.langrid.ws_1_2.foundation.Attribute[] attributes) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setServiceInstance(java.lang.String serviceId, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceInstance instance) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceNotInactiveException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public boolean isServiceVisible(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setServiceVisible(java.lang.String serviceId, boolean visible) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void clear() throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void addService(java.lang.String serviceId, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceProfile profile, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceInstance instance, jp.go.nict.langrid.ws_1_2.foundation.Attribute[] attributes) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceAlreadyExistsException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
}
