/**
 * ResourceManagement.java
 *
 * このファイルはWSDLから自動生成されました / [en]-(This file was auto-generated from WSDL)
 * Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java生成器によって / [en]-(by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.)
 */

package localhost.langrid_1_2.services.ResourceManagement;

public interface ResourceManagement extends java.rmi.Remote {
    public void addResource(java.lang.String resourceId, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceProfile profile, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceInstance instance, jp.go.nict.langrid.ws_1_2.foundation.Attribute[] attributes) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceAlreadyExistsException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceEntrySearchResult searchResources(int startIndex, int maxCount, jp.go.nict.langrid.ws_1_2.foundation.MatchingCondition[] conditions, jp.go.nict.langrid.ws_1_2.foundation.Order[] orders, java.lang.String scope) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.UnsupportedMatchingMethodException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void deleteResource(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotInactiveException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void addResourceAs(java.lang.String ownerUserId, java.lang.String resourceId, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceProfile profile, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceInstance instance, jp.go.nict.langrid.ws_1_2.foundation.Attribute[] attributes) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceAlreadyExistsException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceProfile getResourceProfile(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setResourceProfile(java.lang.String resourceId, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceProfile profile) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceInstance getResourceInstance(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setResourceInstance(java.lang.String resourceId, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceInstance instance) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public jp.go.nict.langrid.ws_1_2.foundation.Attribute[] getResourceAttributes(java.lang.String resourceId, java.lang.String[] attributeNames) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void setResourceAttributes(java.lang.String resourceId, jp.go.nict.langrid.ws_1_2.foundation.Attribute[] attributes) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void activateResource(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void deactivateResource(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public boolean isResourceActive(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void authorizeResource(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void deauthorizeResource(java.lang.String resourceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.resourcemanagement.ResourceNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void clear() throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
}
