// Generated by the protocol buffer compiler.  DO NOT EDIT!

package jp.go.nict.langrid.client.protobuf.proto;

public final class BackTranslationWithTemporalDictionaryProtos {
  private BackTranslationWithTemporalDictionaryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BackTranslateRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use BackTranslateRequest.newBuilder() to construct.
    private BackTranslateRequest() {}
    
    private static final BackTranslateRequest defaultInstance = new BackTranslateRequest();
    public static BackTranslateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public BackTranslateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_fieldAccessorTable;
    }
    
    // repeated .Header headers = 1;
    public static final int HEADERS_FIELD_NUMBER = 1;
    private java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> headers_ =
      java.util.Collections.emptyList();
    public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
      return headers_;
    }
    public int getHeadersCount() { return headers_.size(); }
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
      return headers_.get(index);
    }
    
    // required string sourceLang = 2;
    public static final int SOURCELANG_FIELD_NUMBER = 2;
    private boolean hasSourceLang;
    private java.lang.String sourceLang_ = "";
    public boolean hasSourceLang() { return hasSourceLang; }
    public java.lang.String getSourceLang() { return sourceLang_; }
    
    // required string intermediateLang = 3;
    public static final int INTERMEDIATELANG_FIELD_NUMBER = 3;
    private boolean hasIntermediateLang;
    private java.lang.String intermediateLang_ = "";
    public boolean hasIntermediateLang() { return hasIntermediateLang; }
    public java.lang.String getIntermediateLang() { return intermediateLang_; }
    
    // required string source = 4;
    public static final int SOURCE_FIELD_NUMBER = 4;
    private boolean hasSource;
    private java.lang.String source_ = "";
    public boolean hasSource() { return hasSource; }
    public java.lang.String getSource() { return source_; }
    
    // repeated .bilingualdictionary.Translation temporalDictionary = 5;
    public static final int TEMPORALDICTIONARY_FIELD_NUMBER = 5;
    private java.util.List<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation> temporalDictionary_ =
      java.util.Collections.emptyList();
    public java.util.List<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation> getTemporalDictionaryList() {
      return temporalDictionary_;
    }
    public int getTemporalDictionaryCount() { return temporalDictionary_.size(); }
    public jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation getTemporalDictionary(int index) {
      return temporalDictionary_.get(index);
    }
    
    // optional string dictionaryTargetLang = 6;
    public static final int DICTIONARYTARGETLANG_FIELD_NUMBER = 6;
    private boolean hasDictionaryTargetLang;
    private java.lang.String dictionaryTargetLang_ = "";
    public boolean hasDictionaryTargetLang() { return hasDictionaryTargetLang; }
    public java.lang.String getDictionaryTargetLang() { return dictionaryTargetLang_; }
    
    public final boolean isInitialized() {
      if (!hasSourceLang) return false;
      if (!hasIntermediateLang) return false;
      if (!hasSource) return false;
      for (jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header element : getHeadersList()) {
        if (!element.isInitialized()) return false;
      }
      for (jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation element : getTemporalDictionaryList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header element : getHeadersList()) {
        output.writeMessage(1, element);
      }
      if (hasSourceLang()) {
        output.writeString(2, getSourceLang());
      }
      if (hasIntermediateLang()) {
        output.writeString(3, getIntermediateLang());
      }
      if (hasSource()) {
        output.writeString(4, getSource());
      }
      for (jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation element : getTemporalDictionaryList()) {
        output.writeMessage(5, element);
      }
      if (hasDictionaryTargetLang()) {
        output.writeString(6, getDictionaryTargetLang());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header element : getHeadersList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasSourceLang()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSourceLang());
      }
      if (hasIntermediateLang()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getIntermediateLang());
      }
      if (hasSource()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSource());
      }
      for (jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation element : getTemporalDictionaryList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      if (hasDictionaryTargetLang()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getDictionaryTargetLang());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest result;
      
      // Construct using jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest();
        return builder;
      }
      
      protected jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.getDescriptor();
      }
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest getDefaultInstanceForType() {
        return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.headers_ != java.util.Collections.EMPTY_LIST) {
          result.headers_ =
            java.util.Collections.unmodifiableList(result.headers_);
        }
        if (result.temporalDictionary_ != java.util.Collections.EMPTY_LIST) {
          result.temporalDictionary_ =
            java.util.Collections.unmodifiableList(result.temporalDictionary_);
        }
        jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest) {
          return mergeFrom((jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest other) {
        if (other == jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.getDefaultInstance()) return this;
        if (!other.headers_.isEmpty()) {
          if (result.headers_.isEmpty()) {
            result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
          }
          result.headers_.addAll(other.headers_);
        }
        if (other.hasSourceLang()) {
          setSourceLang(other.getSourceLang());
        }
        if (other.hasIntermediateLang()) {
          setIntermediateLang(other.getIntermediateLang());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (!other.temporalDictionary_.isEmpty()) {
          if (result.temporalDictionary_.isEmpty()) {
            result.temporalDictionary_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation>();
          }
          result.temporalDictionary_.addAll(other.temporalDictionary_);
        }
        if (other.hasDictionaryTargetLang()) {
          setDictionaryTargetLang(other.getDictionaryTargetLang());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder subBuilder = jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHeaders(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setSourceLang(input.readString());
              break;
            }
            case 26: {
              setIntermediateLang(input.readString());
              break;
            }
            case 34: {
              setSource(input.readString());
              break;
            }
            case 42: {
              jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation.Builder subBuilder = jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTemporalDictionary(subBuilder.buildPartial());
              break;
            }
            case 50: {
              setDictionaryTargetLang(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated .Header headers = 1;
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
        return java.util.Collections.unmodifiableList(result.headers_);
      }
      public int getHeadersCount() {
        return result.getHeadersCount();
      }
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
        return result.getHeaders(index);
      }
      public Builder setHeaders(int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.headers_.set(index, value);
        return this;
      }
      public Builder setHeaders(int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        result.headers_.set(index, builderForValue.build());
        return this;
      }
      public Builder addHeaders(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.headers_.isEmpty()) {
          result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
        }
        result.headers_.add(value);
        return this;
      }
      public Builder addHeaders(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (result.headers_.isEmpty()) {
          result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
        }
        result.headers_.add(builderForValue.build());
        return this;
      }
      public Builder addAllHeaders(
          java.lang.Iterable<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> values) {
        if (result.headers_.isEmpty()) {
          result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
        }
        super.addAll(values, result.headers_);
        return this;
      }
      public Builder clearHeaders() {
        result.headers_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string sourceLang = 2;
      public boolean hasSourceLang() {
        return result.hasSourceLang();
      }
      public java.lang.String getSourceLang() {
        return result.getSourceLang();
      }
      public Builder setSourceLang(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSourceLang = true;
        result.sourceLang_ = value;
        return this;
      }
      public Builder clearSourceLang() {
        result.hasSourceLang = false;
        result.sourceLang_ = getDefaultInstance().getSourceLang();
        return this;
      }
      
      // required string intermediateLang = 3;
      public boolean hasIntermediateLang() {
        return result.hasIntermediateLang();
      }
      public java.lang.String getIntermediateLang() {
        return result.getIntermediateLang();
      }
      public Builder setIntermediateLang(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIntermediateLang = true;
        result.intermediateLang_ = value;
        return this;
      }
      public Builder clearIntermediateLang() {
        result.hasIntermediateLang = false;
        result.intermediateLang_ = getDefaultInstance().getIntermediateLang();
        return this;
      }
      
      // required string source = 4;
      public boolean hasSource() {
        return result.hasSource();
      }
      public java.lang.String getSource() {
        return result.getSource();
      }
      public Builder setSource(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSource = true;
        result.source_ = value;
        return this;
      }
      public Builder clearSource() {
        result.hasSource = false;
        result.source_ = getDefaultInstance().getSource();
        return this;
      }
      
      // repeated .bilingualdictionary.Translation temporalDictionary = 5;
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation> getTemporalDictionaryList() {
        return java.util.Collections.unmodifiableList(result.temporalDictionary_);
      }
      public int getTemporalDictionaryCount() {
        return result.getTemporalDictionaryCount();
      }
      public jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation getTemporalDictionary(int index) {
        return result.getTemporalDictionary(index);
      }
      public Builder setTemporalDictionary(int index, jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.temporalDictionary_.set(index, value);
        return this;
      }
      public Builder setTemporalDictionary(int index, jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation.Builder builderForValue) {
        result.temporalDictionary_.set(index, builderForValue.build());
        return this;
      }
      public Builder addTemporalDictionary(jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.temporalDictionary_.isEmpty()) {
          result.temporalDictionary_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation>();
        }
        result.temporalDictionary_.add(value);
        return this;
      }
      public Builder addTemporalDictionary(jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation.Builder builderForValue) {
        if (result.temporalDictionary_.isEmpty()) {
          result.temporalDictionary_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation>();
        }
        result.temporalDictionary_.add(builderForValue.build());
        return this;
      }
      public Builder addAllTemporalDictionary(
          java.lang.Iterable<? extends jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation> values) {
        if (result.temporalDictionary_.isEmpty()) {
          result.temporalDictionary_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.Translation>();
        }
        super.addAll(values, result.temporalDictionary_);
        return this;
      }
      public Builder clearTemporalDictionary() {
        result.temporalDictionary_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string dictionaryTargetLang = 6;
      public boolean hasDictionaryTargetLang() {
        return result.hasDictionaryTargetLang();
      }
      public java.lang.String getDictionaryTargetLang() {
        return result.getDictionaryTargetLang();
      }
      public Builder setDictionaryTargetLang(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDictionaryTargetLang = true;
        result.dictionaryTargetLang_ = value;
        return this;
      }
      public Builder clearDictionaryTargetLang() {
        result.hasDictionaryTargetLang = false;
        result.dictionaryTargetLang_ = getDefaultInstance().getDictionaryTargetLang();
        return this;
      }
    }
    
    static {
      jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.getDescriptor();
    }
    
    static {
      jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internalForceInit();
    }
  }
  
  public static final class BackTranslationResult extends
      com.google.protobuf.GeneratedMessage {
    // Use BackTranslationResult.newBuilder() to construct.
    private BackTranslationResult() {}
    
    private static final BackTranslationResult defaultInstance = new BackTranslationResult();
    public static BackTranslationResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public BackTranslationResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_fieldAccessorTable;
    }
    
    // required string intermediate = 1;
    public static final int INTERMEDIATE_FIELD_NUMBER = 1;
    private boolean hasIntermediate;
    private java.lang.String intermediate_ = "";
    public boolean hasIntermediate() { return hasIntermediate; }
    public java.lang.String getIntermediate() { return intermediate_; }
    
    // required string target = 2;
    public static final int TARGET_FIELD_NUMBER = 2;
    private boolean hasTarget;
    private java.lang.String target_ = "";
    public boolean hasTarget() { return hasTarget; }
    public java.lang.String getTarget() { return target_; }
    
    public final boolean isInitialized() {
      if (!hasIntermediate) return false;
      if (!hasTarget) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasIntermediate()) {
        output.writeString(1, getIntermediate());
      }
      if (hasTarget()) {
        output.writeString(2, getTarget());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIntermediate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIntermediate());
      }
      if (hasTarget()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTarget());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult result;
      
      // Construct using jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult();
        return builder;
      }
      
      protected jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.getDescriptor();
      }
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult getDefaultInstanceForType() {
        return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult) {
          return mergeFrom((jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult other) {
        if (other == jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.getDefaultInstance()) return this;
        if (other.hasIntermediate()) {
          setIntermediate(other.getIntermediate());
        }
        if (other.hasTarget()) {
          setTarget(other.getTarget());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setIntermediate(input.readString());
              break;
            }
            case 18: {
              setTarget(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string intermediate = 1;
      public boolean hasIntermediate() {
        return result.hasIntermediate();
      }
      public java.lang.String getIntermediate() {
        return result.getIntermediate();
      }
      public Builder setIntermediate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIntermediate = true;
        result.intermediate_ = value;
        return this;
      }
      public Builder clearIntermediate() {
        result.hasIntermediate = false;
        result.intermediate_ = getDefaultInstance().getIntermediate();
        return this;
      }
      
      // required string target = 2;
      public boolean hasTarget() {
        return result.hasTarget();
      }
      public java.lang.String getTarget() {
        return result.getTarget();
      }
      public Builder setTarget(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTarget = true;
        result.target_ = value;
        return this;
      }
      public Builder clearTarget() {
        result.hasTarget = false;
        result.target_ = getDefaultInstance().getTarget();
        return this;
      }
    }
    
    static {
      jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.getDescriptor();
    }
    
    static {
      jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internalForceInit();
    }
  }
  
  public static final class BackTranslateResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use BackTranslateResponse.newBuilder() to construct.
    private BackTranslateResponse() {}
    
    private static final BackTranslateResponse defaultInstance = new BackTranslateResponse();
    public static BackTranslateResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BackTranslateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_fieldAccessorTable;
    }
    
    // repeated .Header headers = 1;
    public static final int HEADERS_FIELD_NUMBER = 1;
    private java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> headers_ =
      java.util.Collections.emptyList();
    public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
      return headers_;
    }
    public int getHeadersCount() { return headers_.size(); }
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
      return headers_.get(index);
    }
    
    // optional .Fault fault = 2;
    public static final int FAULT_FIELD_NUMBER = 2;
    private boolean hasFault;
    private jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault fault_ = jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance();
    public boolean hasFault() { return hasFault; }
    public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault getFault() { return fault_; }
    
    // optional .backtranslationwithtemporaldictionary.BackTranslationResult result = 3;
    public static final int RESULT_FIELD_NUMBER = 3;
    private boolean hasResult;
    private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult result_ = jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.getDefaultInstance();
    public boolean hasResult() { return hasResult; }
    public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult getResult() { return result_; }
    
    public final boolean isInitialized() {
      for (jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header element : getHeadersList()) {
        if (!element.isInitialized()) return false;
      }
      if (hasFault()) {
        if (!getFault().isInitialized()) return false;
      }
      if (hasResult()) {
        if (!getResult().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header element : getHeadersList()) {
        output.writeMessage(1, element);
      }
      if (hasFault()) {
        output.writeMessage(2, getFault());
      }
      if (hasResult()) {
        output.writeMessage(3, getResult());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header element : getHeadersList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasFault()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFault());
      }
      if (hasResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getResult());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse result;
      
      // Construct using jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse();
        return builder;
      }
      
      protected jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDescriptor();
      }
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse getDefaultInstanceForType() {
        return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.headers_ != java.util.Collections.EMPTY_LIST) {
          result.headers_ =
            java.util.Collections.unmodifiableList(result.headers_);
        }
        jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse) {
          return mergeFrom((jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse other) {
        if (other == jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance()) return this;
        if (!other.headers_.isEmpty()) {
          if (result.headers_.isEmpty()) {
            result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
          }
          result.headers_.addAll(other.headers_);
        }
        if (other.hasFault()) {
          mergeFault(other.getFault());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder subBuilder = jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHeaders(subBuilder.buildPartial());
              break;
            }
            case 18: {
              jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder subBuilder = jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.newBuilder();
              if (hasFault()) {
                subBuilder.mergeFrom(getFault());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFault(subBuilder.buildPartial());
              break;
            }
            case 26: {
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.Builder subBuilder = jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.newBuilder();
              if (hasResult()) {
                subBuilder.mergeFrom(getResult());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setResult(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .Header headers = 1;
      public java.util.List<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> getHeadersList() {
        return java.util.Collections.unmodifiableList(result.headers_);
      }
      public int getHeadersCount() {
        return result.getHeadersCount();
      }
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header getHeaders(int index) {
        return result.getHeaders(index);
      }
      public Builder setHeaders(int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.headers_.set(index, value);
        return this;
      }
      public Builder setHeaders(int index, jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        result.headers_.set(index, builderForValue.build());
        return this;
      }
      public Builder addHeaders(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.headers_.isEmpty()) {
          result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
        }
        result.headers_.add(value);
        return this;
      }
      public Builder addHeaders(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header.Builder builderForValue) {
        if (result.headers_.isEmpty()) {
          result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
        }
        result.headers_.add(builderForValue.build());
        return this;
      }
      public Builder addAllHeaders(
          java.lang.Iterable<? extends jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header> values) {
        if (result.headers_.isEmpty()) {
          result.headers_ = new java.util.ArrayList<jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Header>();
        }
        super.addAll(values, result.headers_);
        return this;
      }
      public Builder clearHeaders() {
        result.headers_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .Fault fault = 2;
      public boolean hasFault() {
        return result.hasFault();
      }
      public jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault getFault() {
        return result.getFault();
      }
      public Builder setFault(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFault = true;
        result.fault_ = value;
        return this;
      }
      public Builder setFault(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.Builder builderForValue) {
        result.hasFault = true;
        result.fault_ = builderForValue.build();
        return this;
      }
      public Builder mergeFault(jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault value) {
        if (result.hasFault() &&
            result.fault_ != jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance()) {
          result.fault_ =
            jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.newBuilder(result.fault_).mergeFrom(value).buildPartial();
        } else {
          result.fault_ = value;
        }
        result.hasFault = true;
        return this;
      }
      public Builder clearFault() {
        result.hasFault = false;
        result.fault_ = jp.go.nict.langrid.client.protobuf.proto.CommonProtos.Fault.getDefaultInstance();
        return this;
      }
      
      // optional .backtranslationwithtemporaldictionary.BackTranslationResult result = 3;
      public boolean hasResult() {
        return result.hasResult();
      }
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult getResult() {
        return result.getResult();
      }
      public Builder setResult(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder setResult(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.Builder builderForValue) {
        result.hasResult = true;
        result.result_ = builderForValue.build();
        return this;
      }
      public Builder mergeResult(jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult value) {
        if (result.hasResult() &&
            result.result_ != jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.getDefaultInstance()) {
          result.result_ =
            jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.newBuilder(result.result_).mergeFrom(value).buildPartial();
        } else {
          result.result_ = value;
        }
        result.hasResult = true;
        return this;
      }
      public Builder clearResult() {
        result.hasResult = false;
        result.result_ = jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.getDefaultInstance();
        return this;
      }
    }
    
    static {
      jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.getDescriptor();
    }
    
    static {
      jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.internalForceInit();
    }
  }
  
  public static abstract class Service
      implements com.google.protobuf.Service {
    protected Service() {}
    
    public interface Interface {
      public abstract void backTranslate(
          com.google.protobuf.RpcController controller,
          jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest request,
          com.google.protobuf.RpcCallback<jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Service() {
        @Override
        public  void backTranslate(
            com.google.protobuf.RpcController controller,
            jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest request,
            com.google.protobuf.RpcCallback<jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse> done) {
          impl.backTranslate(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.backTranslate(controller, (jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void backTranslate(
        com.google.protobuf.RpcController controller,
        jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest request,
        com.google.protobuf.RpcCallback<jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.backTranslate(controller, (jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest)request,
            com.google.protobuf.RpcUtil.<jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.Service implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void backTranslate(
          com.google.protobuf.RpcController controller,
          jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest request,
          com.google.protobuf.RpcCallback<jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.class,
            jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse backTranslate(
          com.google.protobuf.RpcController controller,
          jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse backTranslate(
          com.google.protobuf.RpcController controller,
          jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest request)
          throws com.google.protobuf.ServiceException {
        return (jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+BackTranslationWithTemporalDictionary." +
      "proto\022%backtranslationwithtemporaldictio" +
      "nary\032\014common.proto\032\031BilingualDictionary." +
      "proto\"\312\001\n\024BackTranslateRequest\022\030\n\007header" +
      "s\030\001 \003(\0132\007.Header\022\022\n\nsourceLang\030\002 \002(\t\022\030\n\020" +
      "intermediateLang\030\003 \002(\t\022\016\n\006source\030\004 \002(\t\022<" +
      "\n\022temporalDictionary\030\005 \003(\0132 .bilingualdi" +
      "ctionary.Translation\022\034\n\024dictionaryTarget" +
      "Lang\030\006 \001(\t\"=\n\025BackTranslationResult\022\024\n\014i" +
      "ntermediate\030\001 \002(\t\022\016\n\006target\030\002 \002(\t\"\226\001\n\025Ba",
      "ckTranslateResponse\022\030\n\007headers\030\001 \003(\0132\007.H" +
      "eader\022\025\n\005fault\030\002 \001(\0132\006.Fault\022L\n\006result\030\003" +
      " \001(\0132<.backtranslationwithtemporaldictio" +
      "nary.BackTranslationResult2\226\001\n\007Service\022\212" +
      "\001\n\rbackTranslate\022;.backtranslationwithte" +
      "mporaldictionary.BackTranslateRequest\032<." +
      "backtranslationwithtemporaldictionary.Ba" +
      "ckTranslateResponseBW\n(jp.go.nict.langri" +
      "d.client.protobuf.protoB+BackTranslation" +
      "WithTemporalDictionaryProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_backtranslationwithtemporaldictionary_BackTranslateRequest_descriptor,
              new java.lang.String[] { "Headers", "SourceLang", "IntermediateLang", "Source", "TemporalDictionary", "DictionaryTargetLang", },
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.class,
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateRequest.Builder.class);
          internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_backtranslationwithtemporaldictionary_BackTranslationResult_descriptor,
              new java.lang.String[] { "Intermediate", "Target", },
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.class,
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslationResult.Builder.class);
          internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_backtranslationwithtemporaldictionary_BackTranslateResponse_descriptor,
              new java.lang.String[] { "Headers", "Fault", "Result", },
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.class,
              jp.go.nict.langrid.client.protobuf.proto.BackTranslationWithTemporalDictionaryProtos.BackTranslateResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          jp.go.nict.langrid.client.protobuf.proto.CommonProtos.getDescriptor(),
          jp.go.nict.langrid.client.protobuf.proto.BilingualDictionaryProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
