/**
 * ServiceDeploymentManagement.java
 *
 * このファイルはWSDLから自動生成されました / [en]-(This file was auto-generated from WSDL)
 * Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java生成器によって / [en]-(by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.)
 */

package localhost.langrid_1_2_N.services.ServiceDeploymentManagement;

public interface ServiceDeploymentManagement extends java.rmi.Remote {
    public jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceDeployment[] listServiceDeployments(java.lang.String serviceId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void addServiceDeployment(java.lang.String serviceId, java.lang.String nodeId, java.lang.String servicePath) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceDeploymentAlreadyExistsException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.NodeNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void deleteServiceDeployment(java.lang.String serviceId, java.lang.String nodeId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceDeploymentNotFoundException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.NodeNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void enableServiceDeployment(java.lang.String serviceId, java.lang.String nodeId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceDeploymentNotFoundException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.NodeNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
    public void disableServiceDeployment(java.lang.String serviceId, java.lang.String nodeId) throws java.rmi.RemoteException, jp.go.nict.langrid.ws_1_2.ServiceNotFoundException, jp.go.nict.langrid.ws_1_2.UnknownException, jp.go.nict.langrid.ws_1_2.InvalidParameterException, jp.go.nict.langrid.ws_1_2.AccessLimitExceededException, jp.go.nict.langrid.ws_1_2.foundation.servicemanagement.ServiceDeploymentNotFoundException, jp.go.nict.langrid.ws_1_2.NoAccessPermissionException, jp.go.nict.langrid.ws_1_2.foundation.NodeNotFoundException, jp.go.nict.langrid.ws_1_2.ServiceConfigurationException;
}
